# Generated by Django 3.0.5 on 2020-05-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrelviewing',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='squirrelviewing',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='squirrelviewing',
            old_name='Longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='squirrelviewing',
            old_name='Shift',
            new_name='shift',
        ),
        migrations.RenameField(
            model_name='squirrelviewing',
            old_name='Unique_Squirrel_Id',
            new_name='unique_squirrel_id',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Approaches',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Chasing',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Climbing',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Eating',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Foraging',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Hectare',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Indifferent',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Kuks',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Moans',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Other_Activities',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Primary_Fur_Color',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Quaas',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Running',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Runs_From',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Specific_Location',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Tail_Flags',
        ),
        migrations.RemoveField(
            model_name='squirrelviewing',
            name='Tail_Twitches',
        ),
        migrations.AddField(
            model_name='squirrelviewing',
            name='date',
            field=models.DateField(blank=True, help_text='Date in the format yyyy-mm-dd', null=True),
        ),
    ]
